### PR TITLE
Add EdgeRolloffFunctor to obs_lsstSim

### PR DESCRIPTION
**Pull request by jchiang87**

### CODE REVIEW

**Comment by PaulPrice** [comment]
You could have done a `git push --force` on the old branch instead of creating a new pull request.

Could you please close the other pull request if it isn't relevant any more?

**Comment by jchiang87** [comment]
I'm happy to do whatever is the right procedure, but Russell asked me to do this. (at least as far as I could tell.)  A little patience would be appreciated as well as some documentation.  In case it is not clear, I don't have direct access to the LSST repos, and I am not familiar with using github this.  Sorry for the noise.

**Comment by PaulPrice** [comment]
It all takes a lot of getting used to.

I'll close the other pull request.  Looking at it, it looks like you must have done a `git push --force`, because it has the same commit SHA.

**Comment by jchiang87** [comment]
Thanks for closing it.  It would be easier to get used to if someone who
knew how things were supposed to work could write some documentation.
Perhaps you could help in that regard?

On Fri, Mar 27, 2015 at 9:53 AM, Paul Price <notifications@github.com>
wrote:

> It all takes a lot of getting used to.
>
> I'll close the other pull request. Looking at it, it looks like you must
> have done a git push --force, because it has the same commit SHA.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lsst/obs_lsstSim/pull/3#issuecomment-87005755>.
>



-- 
James Chiang       SLAC, MS 29          home:   (650) 605-3346
Fermi ISOC         2575 Sand Hill Rd    office: (650) 926-2930
                   Menlo Park CA 94025  FAX:    (650) 926-5566

**Comment by PaulPrice** [comment]
I believe it's currently in flux ([RFC-21](https://jira.lsstcorp.org/browse/RFC-21)).

**Pull request merged**
